# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Outer Coast
email: javier@outercoast.org
description: > # this means to ignore newlines until "baseurl:"
  A new two-year institution of higher education in Sitka, Alaska, inspired by
  Deep Springs College, focused on student self-governance,
  labor & service, and academics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://outercoast.org" # the base hostname & protocol for your site
assetsurl: "https://s3-us-west-2.amazonaws.com/occ-assets/"
imagesurl: "https://s3-us-west-2.amazonaws.com/occ-assets/images/"
twitter_username: outercoastak
github_username:  javbotero

# Build settings
markdown: kramdown
exclude: [vendor] # For travis: http://jekyllrb.com/docs/continuous-integration/
